### ISSUE TITLE
Not working correctly? shows all achievements as misaligned

### ISSUE THREAD

**Issue by JourneyOver** [dannil/HaloAchievementTracker#219]
So I do as the instructions tell me, saving the service record in `Resources\HaloWaypointData` named as `service-record.html`, I grab my `steamId64` and I throw it all into command prompt `HaloAchievementTracker.exe <mysteamId64>` and it just outputs every single achievement as misaligned. looking at it, it doesn't seem to be able to see my steam profile (even though my steam profile is completely public)..

![01-25-2021_17-03-00](https://user-images.githubusercontent.com/13910285/105776995-360f3500-5f2f-11eb-8577-75e4578a8019.png)

**Comment by dannil** [comment]
@JourneyOver thanks for finding this bug. I'm able to reproduce this behavior with my own profile, and have identified what the issue is. I'll release a new version of the app in the coming days which should work correctly.

**Comment by dannil** [comment]
@JourneyOver I've published a beta release of version 2.0.1 which you can find under releases or using [this link](https://github.com/dannil/HaloAchievementTracker/releases/tag/v2.0.1-beta.1). Feel free to write back if it worked for you.

**Comment by JourneyOver** [comment]
Yep looks to be working correctly now :D looks like this issue can now be closed
